name: nak_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/img/nak-letters.png
    - assets/img/nak-emblem.png
    - assets/json/chapters.json
    - assets/img/chapters/

  fonts:
    - family: TrajanPro
      fonts:
        - asset: assets/fonts/TrajanPro-Regular.ttf
        # - asset: assets/fonts/TrajanPro-Bold.otf
          # style: bold
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
